const employees = [
  {
    id: 1,
    firstName: "Ali",
    email: "ali@ali.com",
    password: "123",
    taskCounts: { active: 3, completed: 1, failed: 0, newTask: 2 },
    tasks: [
      {
        taskTitle: "Prepare Monthly Report",
        taskDescription:
          "Compile and analyze sales data for the monthly report.",
        taskDate: "2025-09-20",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Client Meeting",
        taskDescription: "Discuss project requirements with client.",
        taskDate: "2025-09-21",
        category: "Meeting",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Update CRM",
        taskDescription: "Enter new leads into CRM system.",
        taskDate: "2025-09-22",
        category: "Data Entry",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Training Session",
        taskDescription: "Conduct internal training for new employees.",
        taskDate: "2025-09-23",
        category: "Training",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Sara",
    email: "sara.ahmed@company.com",
    password: "123",
    taskCounts: { active: 4, completed: 1, failed: 0, newTask: 3 },
    tasks: [
      {
        taskTitle: "Design Homepage",
        taskDescription: "Create wireframe and UI for homepage.",
        taskDate: "2025-09-23",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix Navbar Bug",
        taskDescription: "Resolve responsive issue in navbar.",
        taskDate: "2025-09-24",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Create Logo",
        taskDescription: "Design a new logo for the company product.",
        taskDate: "2025-09-25",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Update Landing Page",
        taskDescription: "Improve UI for the landing page banner.",
        taskDate: "2025-09-26",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Prepare Presentation",
        taskDescription: "Design slides for upcoming team meeting.",
        taskDate: "2025-09-27",
        category: "Presentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Bilal",
    email: "bilal.hussain@company.com",
    password: "123",
    taskCounts: { active: 5, completed: 2, failed: 1, newTask: 2 },
    tasks: [
      {
        taskTitle: "Database Backup",
        taskDescription: "Perform weekly database backup.",
        taskDate: "2025-09-25",
        category: "Maintenance",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Server Monitoring",
        taskDescription: "Check server logs and performance.",
        taskDate: "2025-09-26",
        category: "IT Support",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Security Patch",
        taskDescription: "Apply latest security patch on servers.",
        taskDate: "2025-09-27",
        category: "Security",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Optimize Database",
        taskDescription: "Run optimization queries for better performance.",
        taskDate: "2025-09-28",
        category: "Database",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "API Integration",
        taskDescription: "Integrate payment API into system.",
        taskDate: "2025-09-29",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "System Testing",
        taskDescription: "Perform QA testing for new release.",
        taskDate: "2025-09-30",
        category: "Testing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Documentation",
        taskDescription: "Update technical documentation for the API.",
        taskDate: "2025-10-01",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Fatima",
    email: "fatima.noor@company.com",
    password: "123",
    taskCounts: { active: 7, completed: 2, failed: 1, newTask: 3 },
    tasks: [
      {
        taskTitle: "Social Media Post",
        taskDescription: "Prepare Instagram and LinkedIn content.",
        taskDate: "2025-09-27",
        category: "Marketing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Email Campaign",
        taskDescription: "Draft email campaign for product launch.",
        taskDate: "2025-09-28",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskTitle: "SEO Update",
        taskDescription: "Improve on-page SEO for product pages.",
        taskDate: "2025-09-29",
        category: "SEO",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Blog Article",
        taskDescription: "Write blog article about new product features.",
        taskDate: "2025-09-30",
        category: "Content Writing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskTitle: "Advertisement Campaign",
        taskDescription: "Launch ad campaign on Facebook and Google.",
        taskDate: "2025-10-01",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Competitor Analysis",
        taskDescription: "Analyze top 5 competitors in the market.",
        taskDate: "2025-10-02",
        category: "Research",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Influencer Outreach",
        taskDescription: "Contact influencers for collaboration.",
        taskDate: "2025-10-04",
        category: "PR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Customer Survey",
        taskDescription: "Prepare and send survey to recent customers.",
        taskDate: "2025-10-05",
        category: "Research",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Event Planning",
        taskDescription: "Organize promotional event for product launch.",
        taskDate: "2025-10-06",
        category: "Event",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Usman",
    email: "usman.raza@company.com",
    password: "123",
    taskCounts: { active: 3, completed: 0, failed: 0, newTask: 2 },
    tasks: [
      {
        taskTitle: "Code Review",
        taskDescription: "Review pull requests from junior developers.",
        taskDate: "2025-09-29",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Deploy App",
        taskDescription: "Deploy new version of app to staging.",
        taskDate: "2025-09-30",
        category: "Deployment",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskTitle: "Fix API Errors",
        taskDescription: "Debug issues in user authentication API.",
        taskDate: "2025-10-01",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@company.com",
    password: "123",
  },
];

export const setLocalStorage = function () {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = function () {
  setLocalStorage();
  const employeesData = JSON.parse(
    localStorage.getItem("employees", employees)
  );
  const adminData = JSON.parse(localStorage.getItem("admin", admin));
  return { employeesData, adminData };
};
